"""add foreign key to Review

Revision ID: 98b8929e386d
Revises: 5e09d45e327c
Create Date: 2024-10-13 07:11:50.463356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b8929e386d'
down_revision = '5e09d45e327c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if 'employee_id' not in [col['name'] for col in conn.execute("PRAGMA table_info(reviews);")]:
        op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
